FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    chromium \
    chromium-driver

COPY . .

RUN pip install -r requirements.txt

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
